import{a as c,R as d,S as f}from"./assets/vendor-CWoPGbCt.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const l=10,p="https://sound-wave.b.goit.study/api",u={GENRES:"/genres",ARTISTS:"/artists",ARTIST_BY_ID:"/artists/",FEEDBACKS:"/feedbacks"};c.defaults.baseURL=p;async function b(){const{data:s}=await c.get(`${u.FEEDBACKS}?limit=${l}&page=1`);return s}const m={feedbacksList:document.querySelector(".swiper-wrapper")};function n(s){const r=s.map(({_id:a,name:o,rating:e,descr:t})=>`
        <div class="swiper-slide">
          <div class="feedback-block">
            <div data-raty class="feedback-rating" data-id=${a} data-score=${e}></div>
            <p class="feedback-descr">${t}</p>
            <p class="feedback-name">${o}</p>
          </div>
        </div>`).join("");m.feedbacksList.insertAdjacentHTML("beforeend",r)}async function y(){const r=(await b()).data;n(r)}y();n(feedbacksArray);const g={starOn:"./img/feedback-img/star-on.png",starOff:"./img/feedback-img/star-off.png",space:!1,readOnly:!0,halfShow:!1},w=Array.from(document.querySelectorAll("[data-raty]"));w.map(s=>{const r=Number(s.dataset.score);new d(s,{...g,score:r}).init()});new f(".swiper",{direction:"horizontal",loop:!1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".swiper-pagination"},scrollbar:{el:".swiper-scrollbar"}});
//# sourceMappingURL=index.js.map
